/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        sans: [
          "Inter",
          "system-ui",
          "-apple-system",
          "Segoe UI",
          "Roboto",
          "Helvetica",
          "Arial",
          "Apple Color Emoji",
          "Segoe UI Emoji",
        ],
        mono: [
          "JetBrains Mono",
          "ui-monospace",
          "SFMono-Regular",
          "Menlo",
          "Monaco",
          "Consolas",
          "Liberation Mono",
          "Courier New",
        ],
      },
      borderRadius: {
        xs: "4px",
        sm: "8px",
        md: "12px",
        lg: "16px",
        xl: "24px",
        pill: "9999px",
      },
      boxShadow: {
        sm: "0 1px 2px rgba(0,0,0,0.06)",
        DEFAULT: "0 6px 18px rgba(0,0,0,0.08)",
        md: "0 6px 18px rgba(0,0,0,0.08)",
        lg: "0 10px 30px rgba(0,0,0,0.12)",
        xl: "0 20px 55px rgba(0,0,0,0.16)",
      },
      colors: {
        // semantic tokens via CSS variables — stays in sync with theme.json
        bg: {
          base: "var(--bg-base)",
          muted: "var(--bg-muted)",
          subtle: "var(--bg-subtle)",
        },
        surface: {
          base: "var(--surface-base)",
          raised: "var(--surface-raised)",
          muted: "var(--surface-muted)",
        },
        text: {
          primary: "var(--text-primary)",
          secondary: "var(--text-secondary)",
          muted: "var(--text-muted)",
          inverted: "var(--text-inverted)",
        },
        border: {
          subtle: "var(--border-subtle)",
          base: "var(--border-base)",
          strong: "var(--border-strong)",
        },
        ring: {
          focus: "var(--ring-focus)",
          hover: "var(--ring-hover)",
        },
        primary: {
          50: "var(--primary-50)",
          100: "var(--primary-100)",
          200: "var(--primary-200)",
          300: "var(--primary-300)",
          400: "var(--primary-400)",
          500: "var(--primary-500)",
          600: "var(--primary-600)",
          700: "var(--primary-700)",
          800: "var(--primary-800)",
          900: "var(--primary-900)",
        },
        secondary: {
          50: "var(--secondary-50)",
          100: "var(--secondary-100)",
          200: "var(--secondary-200)",
          300: "var(--secondary-300)",
          400: "var(--secondary-400)",
          500: "var(--secondary-500)",
          600: "var(--secondary-600)",
          700: "var(--secondary-700)",
          800: "var(--secondary-800)",
          900: "var(--secondary-900)",
        },
        accent: {
          50: "var(--accent-50)",
          100: "var(--accent-100)",
          200: "var(--accent-200)",
          300: "var(--accent-300)",
          400: "var(--accent-400)",
          500: "var(--accent-500)",
          600: "var(--accent-600)",
          700: "var(--accent-700)",
          800: "var(--accent-800)",
          900: "var(--accent-900)",
        },
      },
      transitionTimingFunction: {
        fast: "cubic-bezier(0.2, 0.9, 0.2, 1)",
        base: "cubic-bezier(0.2, 0.8, 0.2, 1)",
        slow: "cubic-bezier(0.2, 0.8, 0.2, 1)",
      },
      transitionDuration: {
        fast: "120ms",
        base: "180ms",
        slow: "260ms",
      },
    },
  },
  plugins: [],
};
